// Curated list of Lucide icon names relevant to habit tracking.
// These map directly to lucide-react-native component names (kebab-case).
export const HABIT_ICONS: string[] = [
  'heart',
  'book-open',
  'dumbbell',
  'droplets',
  'apple',
  'bed',
  'bike',
  'brain',
  'coffee',
  'flame',
  'glasses',
  'leaf',
  'moon',
  'music',
  'pen-tool',
  'pill',
  'smile',
  'sun',
  'utensils',
  'wine',
  'zap',
  'running',
  'footprints',
  'tree-pine',
  'salad',
  'stretch',
  'yoga',
  'swimming',
  'wallet',
  'dollar-sign',
  'pencil',
  'laptop',
  'phone-off',
  'camera',
  'palette',
  'award',
  'target',
  'timer',
  'activity',
  'weight',
];

export const DEFAULT_ICON = 'zap';
